# Generated by Django 5.0.2 on 2024-05-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crnote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='important',
            new_name='Важно',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='Дата_создания',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='Заголовок',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='memo',
            new_name='Описание',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='Пользователь',
        ),
        migrations.RemoveField(
            model_name='task',
            name='datecompleted',
        ),
        migrations.AddField(
            model_name='task',
            name='Дата_выполнения',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
